### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gregmac** [ericpopivker/Command-Line-Encoder#2]
What's the license for this code? No explicit mention I see anywhere (which really means legally, it cannot be used by anyone else).

**Comment by cpina** [comment]
Ping?

**Comment by ericpopivker** [comment]
It is freeware, so you can use it as you see fit.

**Comment by gregmac** [comment]
Created #3 to add a license file using [Unlicense](https://choosealicense.com/licenses/unlicense/) which is probably the closest to 'freeware'. There's also the [WTFPL](https://choosealicense.com/licenses/wtfpl/) which is very simple/permissive or several [others](https://choosealicense.com/appendix/).

It should get a license file though, it's simpler to use for people that need to care about licenses in their dependencies (eg: everyone that publishes any type of software, both commercial and free/open source).

**Comment by Insire** [comment]
Any news on this?

**Comment by ericpopivker** [comment]
Added MIT License.

**Comment by Insire** [comment]
Thank you!
