### ISSUE TITLE
Request for new functionality in FnR tool

### ISSUE THREAD

**Issue by rexrahul** [ericpopivker/Command-Line-Encoder#4]
Hi Eric,  This request is regarding the FnR tool you have developed which is highly used and appreciated by the community.
I am trying to add a feature into this simple and robust program (strictly for personal use). But am unable to do that properly. Can you kindly help me out, since I think it will be a small thing for you but will be very helpful to me.
The feature is;   A dropdown with 3 options, 1) Search and Replace only the content in the files, 2)  Search and Replace in the File names + the Content + , 3)  Search and Replace in the File names + Folder names +Content.

(BTW, you can contact me via email)

Your sincerely,
Rahul  (rahul.yxm@gmail.com)

**Comment by ericpopivker** [comment]
Hi, can you please submit this issue to FNR Github:
https://github.com/zzzprojects/findandreplace/issues

Thanks,

Eric
